clear variables;
close all;

par_names = {
    '2-m temperature', ...
    '30-m temperature', ...
    '10-m wind velocity', ...
    '10-m wind direction', ...
    '30-m wind velocity', ...
    '30-m wind direction', ...
    'boundary layer height (corresponding to critical bulk Richardson = 0.5)', ...
    'height of the layer where the transport length < 100 m ', ...
    'transport length at the first level (about 25-m height)', ...
    'mean transport length in the layer 0-50 m (from the surface)', ...
    'mean transport length in the layer 0-100 m', ...
    'total cloud cover (range0 to 1)', ...
    'low cloud cover (range0 to 1)', ...
    'medium cloud cover (range0 to 1)', ...
    'high cloud cover (range0 to 1)', ...
    'horizontal transport in the boundary layer (obtained by the product of the boundary layer height and the mean wind in the boundary layer)', ...
    'height of the layer where the transport length < 200 m', ...
    'height of the layer where the transport length < 300 m', ...
    'height of the layer where the transport length < 500 m', ...
    'height of the layer where the transport length < 1000 m', ...
    'S parameter of Bultynck-Malet classification (multiplied by a factor 1000)', ...
    'lambda parameter of Bultynck-Malet classificationLambda = LOG10(106 * ABS(S))', ...
    'relative humidity (%) at 300-m height', ...
    'relative humidity in the layer 0-50 m', ...
    'relative humidity at 100-m height (not layer 0-100 m !)', ...
    'wind velocity at 50-m height', ...
    'wind velocity at 100-m height', ...
    'wind velocity at 200-m height', ...
    'wind velocity at 300-m height', ...
    'wind velocity at 500-m height', ...
    'wind velocity at 750-m height', ...
    'wind velocity at 1000-m height' };

fileName = 'D:\Projects\1310195 - Kenniscentrum Luchtkwaliteit\OVL\2015\opaq\opaq_samples_pm10_dayavg_20090101-20151231.h5';

dy = h5read( fileName, '/42N045/day' );
mn = h5read( fileName, '/42N045/month' );
yr = h5read( fileName, '/42N045/year' );

dt = datenum( yr, mn, dy );

obs = h5read( fileName, '/42N045/obs' );
met = h5read( fileName, '/42N045/meteo' );

obs( dt < datenum(2014,1,1) | dt >= datenum(2015,1,1)    ) = [];
met( dt < datenum(2014,1,1) | dt >= datenum(2015,1,1), : ) = [];
dt(  dt < datenum(2014,1,1) | dt >= datenum(2015,1,1)    ) = [];



for k=1:numel(par_names)
    figure( 'Position', [ 100 100 800 400 ] ); 
    yyaxis left;
    plot( dt, obs ); 
    yyaxis right;
    plot( dt, met(:,k) );
    datetick;
    legend( 'obs', par_names{k} )
end

