FROM mcr.microsoft.com/devcontainers/cpp:1-debian-12

USER root
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends ninja-build nasm automake autoconf autoconf-archive libtool pkg-config
RUN mkdir -p /usr/deps/
COPY ./bootstrap.py /usr/
COPY ./vcpkg.json /usr/
COPY ./deps/vcpkg /usr/deps/vcpkg
RUN chmod +x /usr/bootstrap.py
WORKDIR /usr
ENV VCPKG_FORCE_SYSTEM_BINARIES=1
RUN ./bootstrap.py --triplet arm64-linux --clean-after-build