set(VCPKG_TARGET_ARCHITECTURE x64 CACHE STRING "")
set(VCPKG_CRT_LINKAGE dynamic CACHE STRING "")
set(VCPKG_LIBRARY_LINKAGE static CACHE STRING "")
set(VCPKG_CMAKE_SYSTEM_NAME Linux CACHE STRING "")

set(VCPKG_C_FLAGS "-fp-model=precise" CACHE STRING "" FORCE)
set(VCPKG_CXX_FLAGS "-fp-model=precise" CACHE STRING "" FORCE)
set(VCPKG_LINKER_FLAGS "-fuse-ld=lld" CACHE STRING "" FORCE)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/toolchain-linux-intel.cmake" CACHE FILEPATH "")
