set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(CMAKE_C_COMPILER gcc CACHE STRING "")
set(CMAKE_ASM_COMPILER gcc CACHE STRING "")
set(CMAKE_CXX_COMPILER g++ CACHE STRING "")

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)