% test routine for opaq feedforward network...

input = [
  log(1+40.); ...
  log(1+36.); ...
  log(1+250); ...
  log(1+0.4); ...
  -0.5; ...
  1.35; ...
  1
];

disp( input )

[ net, input_PS, target_PS ] = opaq_readffnet( '42R801_net.xml' );

% this guy has again changed...
input_norm = opaq_mapstd('apply',input,input_PS);

output_norm = sim( net, input_norm );

% this guy has again changed...
output = opaq_mapstd( 'reverse', output_norm, target_PS );


fprintf( 'output=%f, exp=%f\n', output,  exp(output)-1 );