# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# __CHAR_UNSIGNED___EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set __CHAR_UNSIGNED___EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The __CHAR_UNSIGNED___COMPILED variable holds the build result for this TRY_RUN().
#
# Source file   : /home/buildbot/bb-master/master/workers/deps-worker/Dependencies_Gcc_Mingw/build/builddeps/netcdf-c/netcdf-c-prefix/src/netcdf-c-build/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/buildbot/bb-master/master/workers/deps-worker/Dependencies_Gcc_Mingw/build/builddeps/netcdf-c/netcdf-c-prefix/src/netcdf-c-build/CMakeFiles/cmTC_be6a7-__CHAR_UNSIGNED___EXITCODE.exe
# Run arguments :
#    Called from: [2]   /tools/toolchains/buildtools/share/cmake-3.7/Modules/CheckCSourceRuns.cmake
#                 [1]   /home/buildbot/bb-master/master/workers/deps-worker/Dependencies_Gcc_Mingw/build/builddeps/netcdf-c/netcdf-c-prefix/src/netcdf-c/CMakeLists.txt

set( __CHAR_UNSIGNED___EXITCODE
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( __CHAR_UNSIGNED___EXITCODE__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)