function [ xx_date, xx_value, st_info ] = query_ircelsos( station, pol, utc_start, utc_end )


saroad_code = struct( ...
  'o3', '44201%20-%20O3', ...
  'no2', '42602%20-%20NO2', ...
  'pm10', '81102%20-%20PM10', ...
  'pm25', '81104%20-%20PM2.5', ...
  'so2', '42401%20-%20SO2', ...
  'co', '42101%20-%20CO', ...
  'bc', '16111%20-%20Black%20Carbon');

url = [ 'http://sos.irceline.be/sos?REQUEST=GetObservation'...
    '&SERVICE=SOS'...
    '&VERSION=1.0.0' ...
    '&offering=' saroad_code.(pol) ...
    '&observedProperty=' saroad_code.(pol) ...
    '&featureofinterest=' station ...
    '&eventTime=' datestr( utc_start, 'yyyy-mm-ddTHH:MM:SS' ) '/' datestr( utc_end, 'yyyy-mm-ddTHH:MM:SS' ) ...
    '&responseFormat=text/xml;subtype=%22om/1.0.0%22' ];

  % retrieve the datA...
  res = urlread( url );
  fid = fopen( 'temp.xml', 'w' );
  fprintf( fid, '%s', res );
  fclose(fid);
  xml = parseXML( 'temp.xml' );
  delete( 'temp.xml' );
  
  try
    [ xx_date, xx_value, st_info ] = parseSOS( xml );
  catch ME
    throw( MException( sprintf( 'Error getting values for %s', station ) ) );
  end
