name: Vcpkg build (Unix)
permissions:
  packages: write

on: [push]

jobs:
  build:
    name: ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, id: linux }
          - { os: macos-latest, id: mac }

    env:
      USERNAME: VITObelgium
      FEED_URL: https://nuget.pkg.github.com/VITObelgium/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/VITObelgium/index.json,readwrite"

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Install devenv
        run: nix profile install --accept-flake-config nixpkgs#devenv
      - name: Set macOS SDK root
        if: runner.os == 'macOS'
        run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      - name: Add NuGet sources
        run: |
          devenv shell -- bash -c '
            mono $(vcpkg fetch nuget | tail -n 1) \
              sources add \
              -Source "${{ env.FEED_URL }}" \
              -StorePasswordInClearText \
              -Name GitHubPackages \
              -UserName "${{ env.USERNAME }}" \
              -Password "${{ secrets.VCPKG_PAT_TOKEN }}"
            mono $(vcpkg fetch nuget | tail -n 1) \
              setapikey "${{ secrets.VCPKG_PAT_TOKEN }}" \
              -Source "${{ env.FEED_URL }}"
          '
      - name: Build the code
        id: build
        run: devenv shell -- just build
      - name: Run the unit tests
        run: devenv shell -- just test
      - name: Archive build logs
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cfg.id }}-build-logs
          path: |
            vcpkg_installed/vcpkg/buildtrees/**/autoconf*.log
            vcpkg_installed/vcpkg/buildtrees/**/config*.log
            vcpkg_installed/vcpkg/buildtrees/**/build*.log
            vcpkg_installed/vcpkg/buildtrees/**/install*.log
            vcpkg_installed/vcpkg/buildtrees/**/package*.log
