name: Vcpkg build (Unix)

on: [push]

jobs:
  build:
    name: ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, id: linux }
          - { os: macos-latest, id: mac }

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Install devenv
        run: nix profile install --accept-flake-config nixpkgs#devenv
      - name: Set macOS SDK root
        if: runner.os == 'macOS'
        run: echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      - name: Build the code
        id: build
        run: devenv shell -- just build
      - name: Run the unit tests
        run: devenv shell -- just test
      - name: Archive build logs
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cfg.id }}-build-logs
          path: |
            vcpkg_installed/vcpkg/buildtrees/**/autoconf*.log
            vcpkg_installed/vcpkg/buildtrees/**/config*.log
            vcpkg_installed/vcpkg/buildtrees/**/build*.log
            vcpkg_installed/vcpkg/buildtrees/**/install*.log
            vcpkg_installed/vcpkg/buildtrees/**/package*.log
