name: Vcpkg build (Windows)
permissions:
  packages: write

on: [push]

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    env:
      USERNAME: VITObelgium
      FEED_URL: https://nuget.pkg.github.com/VITObelgium/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/VITObelgium/index.json,readwrite"

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Add NuGet sources
        shell: pwsh
        run: |
          .$(vcpkg fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.VCPKG_PAT_TOKEN }}"
          .$(vcpkg fetch nuget) `
            setapikey "${{ secrets.VCPKG_PAT_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: Build the code
        id: build
        run: just build
      - name: Run the unit tests
        run: just test
      - name: Archive build logs
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-logs
          path: |
            ${{ runner.temp }}/vcpkg/buildtrees/**/autoconf*.log
            ${{ runner.temp }}/vcpkg/buildtrees/**/config*.log
            ${{ runner.temp }}/vcpkg/buildtrees/**/build*.log
            ${{ runner.temp }}/vcpkg/buildtrees/**/install*.log
            ${{ runner.temp }}/vcpkg/buildtrees/**/package*.log
